src/nationGen/NationGen.java

Re-implemented fix that was overwritten by 0.5.0.09E commit.

Re-implemented #hidevanillanations fix

---

data/filters/default_priestfilters.txt
data/poses/caelian/troops.txt
data/poses/hoburg/troops.txt
data/poses/human/humanranged.txt
data/poses/lizard/ranged.txt
data/templates/templates.txt
data/themes/default_themes.txt
data/themes/themes.txt
src/nationGen/NationGen.java
src/nationGen/entities/Entity.java
src/nationGen/entities/Theme.java
src/nationGen/magic/MageGenerator.java
src/nationGen/misc/ChanceIncHandler.java
src/nationGen/naming/DescriptionReplacer.java
src/nationGen/nation/Nation.java

Theme pull

---

data/items/hoburg/mounted/mounts.txt
data/items/vaettir/mounted/weapons.txt
data/items/vaettir/normal/bonusranged.txt
data/items/vaettir/normal/weapon.txt
data/items/vaettir/ranged/archerweapon.txt
data/items/vaettir/ranged/bows.txt
data/monsters/default_monsters.txt
data/poses/vaettir/troops.txt
data/races/vaettir.txt
data/themes/vaetti_themes.txt

- Tweaking vaetti themes more
- Gave hoburgs crocodiles, with the venerable, traditional justification of "Why not?"
- Hydra hatchlings had the same problem as hydras in the monster file

Theme updates, hydra hatchling fix

---

data/filters/default_magefilters.txt
data/filters/default_nationfilters.txt
data/items/customitems.txt
data/races/vaettir.txt
src/nationGen/nation/Nation.java

Gotta do some unit generation reworking even if I'm a bit more motivated on descriptions and names, so I'll merge in the minor tweaks I did .

Minor changes before (hopefully) more major stuff

---

data/items/abysian/abysian_helmet.txt
data/items/abysian/humanhelmet_metal.txt
data/items/advancedhuman/normal/armor_elite.txt
data/items/advancedhuman/normal/helmet.txt
data/items/amazon/normal/humanhelmet_amazon.txt
data/items/atlantian/meteorweapon.txt
data/items/atlantian/weapon.txt
data/items/human/normal/humanhelmet.txt
data/items/oriental/normal/helmet.txt
data/items/sobek/predator/predator_helmet.txt
data/items/sobek/predator/runner_helmet.txt

- Updating elite tags to themes
- Verifying there weren't sacred tags

#tag "elite" -> #theme "elite"

---

data/items/gaian/minotaur/2h_armor.txt

Furs != leather cuirass, so they shouldn't look for leathercuirass.png

Minotaur furs fix

---

src/nationGen/rostergeneration/CommanderGenerator.java

1/2 of bad national commanders get #command 20; 1/16 get #command 40
#gcost +10

More better bad commanders

---

data/items/amazon/mounted/amazon_overlays.txt
data/items/amazon/mounted/amazonmounts.txt
data/items/human/human_mounted/humanmounts.txt
data/names/nations/romance/longsyllables.txt
data/names/nations/romance/shortsyllables.txt
data/names/nations/romance/suffixes.txt
data/poses/amazon/amazoncavalry.txt
data/poses/amazon/amazoninfantry.txt
data/poses/amazon/amazonranged.txt
data/races/advancedhumans.txt

Advanced human placenames

---

data/items/gaian/minotaur/2h_bases.txt
data/items/gaian/minotaur/2h_weapon.txt
data/items/gaian/minotaur/bases.txt
data/items/gaian/minotaur/bases_caster.txt
data/items/gaian/minotaur/polearm.txt
data/poses/gaian/minotaurtroops.txt
data/races/minotaurs.txt
data/templates/sloth_magetemplate.txt
data/templates/templates.txt
data/themes/minotaur_themes.txt

40g -> 30g;
+2 att/+1 def;
civilized split into hoplites (formationfighter, +1 mor, spear/trident/longspear/pike) and other
soldiers (trample, +1 def, any weapon w/ DW possible)

Minotaur tweaks

---

data/items/gaian/minotaur/2h_bases.txt
data/items/gaian/minotaur/bases.txt
data/items/gaian/minotaur/bases_caster.txt
data/poses/gaian/minotaurtroops.txt

Forgot to chop berserk in half

Minotaur berserk fix

---

data/races/abysian.txt
data/races/agarthans.txt
data/races/atlantian.txt
data/races/avvim.txt
data/races/caelians.txt
data/races/cavemen.txt
data/races/fomorians.txt
data/races/hoburg.txt
data/races/ichtyid.txt
data/races/machakans.txt
data/races/monkeys.txt
data/races/muuch.txt
data/races/sidhe.txt
data/races/vaettir.txt
data/races/zotz.txt
data/themes/amazon_themes.txt
data/themes/hoburg_themes.txt
data/themes/lizard_themes.txt
data/themes/vaetti_themes.txt

Set a whole bunch of #likespop commands for thematically appropriate
themes and races

Allied poptypes for races and themes

---

src/nationGen/naming/NationAdvancedSummarizer.java

Slow to recruit wasn't being output in advanced descriptions

---

data/items/hoburg/normal/normal_sacredbonusweapons.txt
data/poses/hoburg/troops.txt

Moderately low probability bat wings for the more civilized/non-fae sacred hoburgs (~1/4 the frequency of wings for human sacreds, when applicable)

Non-stealthy hoburg wings

---

data/items/hoburg/crossbow/bows.txt
data/items/hoburg/crossbow/weapon.txt
data/items/hoburg/mounted/mounts.txt
data/items/hoburg/mounted/overlay.txt
data/items/hoburg/mounted/stealthymounts.txt
data/items/hoburg/normal/bonusranged.txt

Themed hoburg mounts into mostly-overlapping region; added grey parrots
and hyenas

Regional hoburg mounts

---

src/nationGen/naming/Summary.java

Slightly cleaner fix of the cav quotation bug that also fixes it for
sacred cavalry, unlike the prior "fix"

Re-fixing cav fix

---

data/items/hoburg/clockwork/armor_clockwork_heavy.txt
data/items/hoburg/clockwork/bronze/armor_clockwork_heavy.txt
data/items/hoburg/clockwork/bronze/specialslots_clockwork_heavy.txt
data/items/hoburg/clockwork/oriental/armor_clockwork_heavy.txt
data/items/hoburg/clockwork/oriental/specialslots_clockwork_heavy.txt
data/items/hoburg/clockwork/specialslots_clockwork_heavy.txt
data/poses/hoburg/clockworktroops.txt
data/poses/hoburg/clockworktroops_bronze.txt
data/poses/hoburg/clockworktroops_oriental.txt
src/nationGen/rostergeneration/SacredGenerator.java

+10 rcost
#sacredratingmulti *0.75
#sacredcostmulti *1.25
Fear *1.2 gcost -> *1.25 gcost
Minimum 0.9 chance of caponly

Heavy clockwork rebalancing

---

data/filters/default_elitefilters.txt
data/filters/default_magefilters.txt
data/filters/default_sacredfilters.txt

Devils, vine/metalmen, deepone to full age of second form; werefoo *2

Gave several shapechange filters increased #maxage 

---

data/filters/default_magefilters.txt
data/filters/default_sacredfilters.txt

- "can shapechange into..." only for #shapechange
- changed all sacred #shapechanges to #secondshape

Shapechange description and command fixes

---

data/poses/ichtyid/mages.txt

+2 mr/-2 res (in line with talented Pelagian ichtyid mages rather than
the "how did these things learn magic?" indy shamans)

Ichtyid mages res penalty/mr bonus

---

data/poses/ichtyid/mages.txt

I agree that the prior change was probably too slavish to canon w/o
regard for balance. The following is what I scaled it back to, though
I'm not wedded to this either.
T1: +1 MR, -2 res
T2: +2 MR, -1 res
T3: +3 MR, -0 res
It may make it so it's inefficient to have hordes of T1 labrats, but
it's not the worst thing in the world if some nations are better off
with fewer stronger researchers.

Ichtyid mage scaled stupidity

---

data/filters/default_sacredfilters.txt

Changed seasonal sacred filters from 1 -> 25; added less common filters
at 50
Closes #269

Seasonal powers fix

---

data/monsters/default_monsters.txt
src/nationGen/misc/ChanceIncHandler.java
src/nationGen/rostergeneration/MonsterGenerator.java

When selecting monsters, the monsters' themes were not triggering
themeincs in the nation's theme. This has been corrected, although my
"solution" is better described in terms relating to pasta than those
relating to good programming practices.

Monsters were not processing themeincs

---

changelog.txt
data/items/abysian/humanbred/humanmounts.txt
data/items/caelian/mage/wings-T1.txt
data/items/caelian/mage/wings-T2.txt
data/items/caelian/mage/wings-T3.txt
data/items/caelian/normal/wings.txt
data/items/customitems.txt
data/items/human/human_mounted/humanmounts.txt
data/items/human/human_mounted/humanmounts_low.txt
data/items/monkey/vanara/mounted/mounts.txt
data/items/sidhe/sidhemounts_low.txt
data/items/vaettir/mounted/mounts.txt
data/misc/startaffinities.txt
data/monsters/default_monsters.txt
data/names/magenames/tieredpriestnames.txt
data/races/agarthans.txt
data/races/caelians.txt
data/races/cavemen.txt
data/races/muuch.txt
data/races/zotz.txt

* I still need to do ice/bronze weapons/shields/helms for Caelians, but that should be it

Namechanges and changelog

---

data/poses/amazon/meticinfantry.txt
data/poses/amazon/meticranged.txt
data/poses/caelian/troops.txt
data/poses/human/humancavalry.txt
data/poses/human/humaninfantry.txt
data/poses/human/humanranged.txt

Helmets go on your head, not your torso

---

data/items/hoburg/clockwork/bases_clockwork_heavy.txt

...putting the empty sprite back...

Heavy clockwork basesprite "fix" fix

---

changelog.txt

Updating the changelog to reflect everything completed prior to your code changes

Changelog update

---

data/items/foulspawn/small/bases.txt
data/items/foulspawn/small/head.txt
data/items/foulspawn/small/headweapon.txt
data/items/foulspawn/small/larm.txt
data/items/foulspawn/small/lleg.txt
data/items/foulspawn/small/lweapon.txt
data/items/foulspawn/small/offhand.txt
data/items/foulspawn/small/rarm.txt
data/items/foulspawn/small/rleg.txt
data/items/foulspawn/small/rweapon.txt
data/items/foulspawn/small/stub_mounts.txt
data/items/foulspawn/small/weapon.txt
data/poses/foulspawn/small/infantry.txt

* Current setup is sufficient to generate unarmed foulspawn with varied stats, costs, and abilities
* Currently since there's no weapons or armor, the almost-functional nations may end up with weaponless foulspawn since free fists are turned off to avoid having both tentacles and fists
* Unit item slots still need figured and added - I'm not sure this will be feasible to do w/o special commands, but I managed to get pretty complicated with hoburg clockworks, so I might be able to figure out how to cleverly manage it with existing tools

Basic fixed-form unarmed foulspawn nations

---

data/items/abysian/demonbred_offhand.txt
data/items/abysian/demonbred_weapon.txt

Flail is two handed and should be with those stats. Now they're morning stars.

Demonbred one handed flails were... one handed.

---

documentation/itemslots.txt
src/nationGen/units/Unit.java

- Ability to add or remove slots from items/filters/whatever
- Mounted units lose feet slot

Dynamic item slot setting

---

data/items/monkey/vanara/mounted/bases.txt
data/items/monkey/vanara/mounted/sacredbases.txt
data/poses/monkey/vanaraelites.txt

* Made monkey chariots use mounted-specific basesprites that don't grant flying even if they have wings
* Closes #477

Less-interesting chariot fix than adding wings to the tigers

---

data/poses/amazon/amazoncavalry.txt
data/poses/amazon/amazonmage.txt
data/races/foulspawn.txt

* Finally fixed the error introduced in my ancient sloppy Amazon cavalry definitions when that one thing with mounted unit generation got fixed or cleaned up a few months back

Fixed Amazon mount overlay issue

---

changelog.txt
data/poses/ogre/caster_ogre.txt
data/poses/poses.txt
data/themes/ogre_themes.txt

- Enough stubs so that *technically* really crappy ogre nations can be generated right now

Ogres (stub structures)

---

data/items/ogre/helmet_ogre.txt
data/poses/poses.txt
data/races/ogres.txt
data/templates/default_freetemplates.txt
data/themes/boreal_themes.txt

* Fixed/"fixed" a couple of data error crashes/inconsistencies
* Added a missing militia template

Crash fixes

---

data/items/ogre/offhand_caster.txt
data/items/ogre/robes.txt
data/poses/ogre/caster_obakemono.txt
data/poses/ogre/caster_ogre.txt
data/poses/ogre/infantry_obakemono.txt
data/races/ogres.txt
src/nationGen/rostergeneration/ScoutGenerator.java

* Also, tweaked the gradiant scout colors down from 150/105/60 to 120/90/60 since Scouts looked a bit off with merely dull grey cloaks - this way it'll be more like a light charcoal for them

Dumb ogre bugfixes

---

changelog.txt
documentation/commandline.txt
src/nationGen/GUI/CommandLine.java
src/nationGen/GUI/GUI.java

This has been requested a couple of times. A simple and somewhat error
prone one is easy to code.

Very rough commandline GUI and changelog

---

data/filters/default_sacredfilters.txt

* So apparently I *very cleverly* added a sacred #undying filter a year or two ago despite there not being a mod command for undying. It's commented out in case whining to the devs for a new mod command bears fruit.

Disable useless filter

---

changelog.txt

Changelog errata

---

data/items/halfmen/centaur/bases_centaur.txt
data/items/halfmen/centaur/bases_centauride.txt

All vanilla centaurs seem to have them.

Hooves for centaurs

---

data/themes/default_nationthemes.txt
src/nationGen/magic/MageGenerator.java
src/nationGen/rostergeneration/TroopGenerator.java

- Priest costing tweaks
- Troop template bugfix

Tweaks and bugfixes

---

data/spells/custom_spells.txt
data/spells/random_spells.txt
data/spells/spells.txt
documentation/list_of_chanceincs.txt
settings.txt
src/nationGen/NationGen.java
src/nationGen/Settings.java
src/nationGen/entities/Filter.java
src/nationGen/magic/Spell.java
src/nationGen/magic/SpellGen.java
src/nationGen/misc/ChanceIncHandler.java
src/nationGen/misc/Command.java
src/nationGen/naming/NationAdvancedSummarizer.java
src/nationGen/nation/Nation.java

This is what I wrote in #518 pretty much exactly. It seems to work fine and is enabled now, but it seriously needs more spells boringly plucked from database before it can be enabled on a release (nation.java contains the code that calls generator).
I'll look into making content tomorrow.

SpellGen code

---

src/nationGen/NationGen.java
src/nationGen/magic/SpellGen.java
src/nationGen/nation/Nation.java
src/nationGen/units/ShapeChangeUnit.java
src/nationGen/units/Unit.java

Spells, shapechanges and custom items were stored to be written even if
nation did not pass restrictions.

Restricted nations left stuff into memory

---

data/names/troopnaming/troopspecialprefixes.txt
data/templates/gladiatortemplate.txt
data/templates/slavetemplate.txt
documentation/list_of_chanceincs.txt
src/nationGen/misc/ChanceIncHandler.java

* Added chanceinc to detect [not] secondaryraces so illithid nations can have secondary-specific lobo guards
* Lobo slave templates and name prefixes

Added secondaryrace chanceinc and illithid lobo framework

---

data/themes/primate_themes.txt

Forgot to save these changes before committing the rest of this stuff

Primate subrace prefixes

---

data/items/illithid/slave/thrall_agarthan.txt
data/items/illithid/slave/thrall_atlantian.txt
data/items/illithid/slave/thrall_hoburg.txt
data/items/illithid/slave/thrall_human.txt
data/items/illithid/slave/thrall_muuch.txt
data/items/illithid/slave/thrall_vanara.txt
data/items/illithid/slave/weapon_thrall.txt

(In case it isn't clear, humans are given claws in keeping with ghouls and maenads being clawed.)

Functional thrall weapon selection

---

src/nationGen/rostergeneration/CommanderGenerator.java

National commanders who are mindless but not magic beings cannot be inspiring; non-magical mindless animals and slaves will be treated as non-animals/non-slaves (and thus subject to the same chances to get the same bonuses to taskmaster/beastmaster as non-animals/slaves).

Uninspiring mindless beings

---

src/nationGen/naming/DescriptionReplacer.java

Remove a printout used for debug

---

src/nationGen/rostergeneration/CommanderGenerator.java

* Much more likely for taskmasters/beastmasters to show up when there are slaves or animals
* magicbeing/undead/demon commanders are more likely to have increased leadership over their own kind, though possibly worse with normal troops
* Normal commanders in nations with many special troops more likely to have increased leadership over them, though possibly slightly worse with normal troops
* Special leadership in the above two cases can potentially reach expert leadership with such troops (though this will be quite rare)
* Special leadership is generally slightly less likely for national commanders without special national troops (50% chance for each of magic and undead leadership power passed to the special leadership calculation method to be one level lower); I'm iffy about this since …

Special leadership revisions for generic commanders

---

data/items/hoburg/caster/robes.txt
data/items/hoburg/ghoul/bases.txt
data/items/hoburg/ghoul/claw.txt
data/items/hoburg/ghoul/hands.txt
data/poses/hoburg/stealthytroops.txt
data/poses/hoburg/troops.txt
data/shapes/secondshapes.txt

* Hoburg ghoul definitions for boreal hoburg nations with death magic
* Fixed some predictable dumb errors with hoburg Nazca robes arising from not spritetesting before committing

Boreal hoburg ghouls

---

data/items/hoburg/ghoul/bases.txt
data/items/hoburg/ghoul/claw_oh.txt
data/items/human/boreal/ghoul/bases.txt
data/items/human/boreal/ghoul/blacksteelarmor.txt
data/items/human/boreal/ghoul/blacksteelhelmet.txt
data/items/human/boreal/ghoul/claw.txt
data/items/human/boreal/ghoul/claw_oh.txt
data/items/human/boreal/ghoul/hands.txt
data/poses/hoburg/stealthytroops.txt
data/poses/hoburg/troops.txt
data/poses/human/blacksteeltroops.txt
data/poses/human/humaninfantry.txt

* Ghoul infantry as a possible unit for boreal human nations with death magic. If they have blacksteel as well, they can have blacksteel ghouls.
* No cavalry or mages at this time

Normal and blacksteel ghoul infantry

---

data/items/caelian/mage/armor.txt
data/items/dynastichuman/chariot/bonusranged_dustwalker.txt

* filename fix for Caelian robe: nazca_white_medium.png -> nazca_white_grey.png
* removed copy-pasted quiver dependency for dustwalker chariot bonusweapons

Bug fixes from the thread

---

data/items/halfmen/centaur/armor_centaur.txt
data/items/halfmen/centaur/armor_centauride.txt
data/items/halfmen/centaur/armor_light_centaur.txt
data/items/halfmen/centaur/armor_light_centauride.txt
data/items/hoburg/ghoul/bases.txt
data/items/human/boreal/ghoul/bases.txt
data/poses/halfmen/centaurmages.txt
data/races/tengu.txt

* Tengus should all be storm-immune zappers
* Centaurs are only as stealthy as vanilla ones
* Ghouls are #poisonres instead of being able to #resistpoison

Most recent thread bugs

---

src/nationGen/items/CustomItemGen.java
src/nationGen/rostergeneration/RosterGenerator.java

Tengu rosters and magic twohanders wielded with shields fixed. See commit comments for more info.

0.6.18 bugfixes

---

src/nationGen/rostergeneration/CommanderGenerator.java

The reported crash is due to possibleCommanders being empty. Can't
reproduce with this branch so I'm not gonna find out why, so I'm just
adding a failsafe it should have anyway.

New failsafe for commander generator

---

data/items/machakans/archer/bases.txt
data/items/machakans/mounted/bases.txt
data/poses/machakan/troops.txt
data/races/machakans.txt

* Moved the mapmove 3 entirely out of the race file and added a mounted-specific bases file to ensure they received default mapmove instead of the boosted infantry speed.

Austral human cavalry (and pygmies) were too fast

---

src/nationGen/rostergeneration/SacredGenerator.java

Morale had some stupid code still and I wanted to tweak things a bit to
make them less deterministic.

More sacred morale and magic resistance tweaks

---

data/items/dynastichuman/bases_dustwalker_chariot.txt

I heard these are pretty op. This is a very soft nerf.

Reclimit for dustwalker chariots

---

data/items/illithid/illithid/mental_attack.txt
data/items/illithid/illithid/weapon_bonus.txt
data/items/illithid/illithid/weapon_mindflayer.txt
data/items/illithid/starchild/mental_attack.txt
data/items/illithid/starchild/weapon_mindflayer.txt

Mental attacks were getting magic variants with wierd results

---

data/items/dynastichuman/archer/bows_dustwalker.txt
data/items/dynastichuman/chariot/bonusranged_dustwalker.txt
data/items/hoburg/crossbow/bows.txt
data/items/hoburg/crossbow/weapon.txt
data/items/human/scout/bonusranged_scout.txt

(Mostly but not only poison slings)

Excluding some weapons from further upgrade

---

data/poses/hoburg/clockworktroops.txt
data/poses/hoburg/clockworktroops_bronze.txt
data/poses/hoburg/clockworktroops_oriental.txt
documentation/special_commands.txt
src/nationGen/rostergeneration/SacredGenerator.java
src/nationGen/rostergeneration/TroopGenerator.java

...this can be used for four armed things if it is expanded via cleanUnit() to all units instead of troops!

Hoburg fixes and #additionalweaponslot

---

changelog.txt

(This isn't suggesting we need to do a release soon or anything; I'm just trying to be proactive.)

Periodic changelog update

---

changelog.txt
data/filters/default_magefilters.txt
data/filters/default_sacredfilters.txt

* Growthpower, airshield, and overcharged for sacreds
* Airshield for mages
* Tweaked deathpower so it won't mistake growthpower for itself
* Fixed a couple of typos in the sacred filter file
* In re: #804

Some new filters

---

data/filters/default_elitefilters.txt
data/filters/default_magefilters.txt
data/filters/default_sacredfilters.txt
src/nationGen/units/Unit.java

See #839 for discussion of changes.

%cost fixes, updated #addupkeep filters

---

data/filters/default_elitefilters.txt

I managed to avoid uploading these with the other stuff, d'oh.

Actual bloodguard filters

---

src/nationGen/nation/Nation.java
src/nationGen/nation/PDSelector.java

Sadly this did not work for start armies, but oh well, the PD is the most important part.

Montag PD support

---

data/items/agarthan/generic_big/bases_ageless.txt
data/items/agarthan/generic_big/cloakb_ageless.txt
data/items/agarthan/generic_big/cloakf_ageless.txt
data/items/agarthan/generic_big/magearmor_ageless.txt
data/monsters/default_monsters.txt
data/poses/agarthan/agarthanmages.txt

* Stat-wise, watered-down Earth-Made-Flesh-es; basically huge lumpy bags of sacred HP

Ageless one monsters/mage-heroes

---

changelog.txt
data/items/customitems.txt
data/items/fomorian/weapon.txt
data/items/fomorian/weapon_caster.txt
data/items/sidhe/bonusweapon.txt
data/items/sidhe/weapon.txt
data/items/sidhe/weapon_mages.txt
data/names/troopnaming/troopmiscitemnames.txt
data/names/troopnaming/troopmiscitemprefixes.txt
data/names/troopnaming/troopspecialnames.txt
data/names/troopnaming/troopweaponnames.txt
data/names/troopnaming/troopweaponprefixes.txt

*Fomorian longspears and sidhe axes/lances

Celtic weapon fixes

---

data/monsters/default_monsters.txt
data/monsters/hoburg_monsters.txt
data/themes/hoburg_themes.txt

* I'm pretty sure I got rid of these because of specified costs not working, but the #specifiedgcost tag I implemented for giant hoburgs fixes that

Re-added FS big ugly monsters

---

src/nationGen/rostergeneration/CommanderGenerator.java

Right now, if commanders have 120 leadership they cost 2RP, else 1RP

Very simple commander recpoints

---

src/nationGen/entities/Race.java
src/nationGen/nation/Nation.java

- Anything giving +X to a command nation did not have was handled wrong.
- Nations did not take nation commands of races from race themes into account at all.
This closes #942

Bugs related to nation and race themes

---

data/filters/default_magefilters.txt
data/filters/default_magefilters_strongdefence.txt
data/filters/default_magefilters_strongdefence_expensive.txt

Removed/simplified conditional chanceincs from mage filters, as there
appears to be a problem with them, or possibly just with personalmagic
and them. I'm not alert enough tonight to try to figure out if the
problem is conditionals, personalmagic, or my use of conditionals, but I
may revisit examining this when I'm more able.

Filter fix

---

data/misc/forts.txt
data/misc/forts_city.txt
data/misc/forts_giant.txt
data/misc/forts_ice.txt
data/misc/miscdef.txt
data/races/atlantian.txt
data/races/avvim.txt
data/races/dynastichumans.txt
data/races/elephantmen.txt
data/races/enlightened.txt
data/races/fomorians.txt
data/races/lizards.txt
data/races/muuch.txt
data/races/nagas.txt
data/races/ogres.txt
data/races/orientalhuman.txt
data/races/zotz.txt
data/themes/amazon_themes.txt
data/themes/austral_themes.txt
data/themes/caelian_themes.txt
data/themes/default_racethemes.txt
data/themes/hoburg_themes.txt
data/themes/primate_themes.txt
data/themes/serpentmen_themes.txt
src/nationGen/naming/NationAdvancedSummarizer.java

* Added advanced late era fort level to default_forts
* Added [fortified villages->wooden forts] to default_forts
* Added giant_forts, city_forts, and ice_forts; various races/themes were assigned these in place of/in addition to default_forts
* Updated Advanced Descriptions to indicate if a nation builds giant/city/ice/village forts (default forts produce no special output)

Nonstandard fort support

---

src/nationGen/misc/ChanceIncHandler.java

* #chanceinc race <value> was checking whether <value> == "race"

Fixed #chanceinc race <value>

---

data/items/hoburg/crossbow/weapon.txt
data/items/hoburg/normal/bonusranged.txt
data/items/vaettir/normal/bonusranged.txt
data/items/vaettir/ranged/bows.txt
data/monsters/default_monsters.txt
data/monsters/hoburg_monsters.txt
data/names/sacredbasenames.txt
data/names/sacredcommandernames.txt
data/names/troopnaming/commanderbasenames.txt

* Got rid of lingering small bows
* Some imperial commander names
* Some lingering sirrush replacement

Small bows, imperial names

---

src/nationGen/GUI/GUI.java
src/nationGen/NationGen.java

This should in combination with my fix for UI stability greatly enhance the user experience.

Add a Pause and Abort while Exporting button.

---

src/nationGen/CustomItemsHandler.java
src/nationGen/NationGen.java
src/nationGen/entities/Pose.java
src/nationGen/items/CustomItemGen.java
src/nationGen/units/Unit.java

Most of the code was just shifted so it's honestly a fairly simple refactoring. 
For regressions, my testing is generating a set of 5 seeded nations & comparing the output file.

Refactor custom items into separate class

---

settings.txt
src/nationGen/GUI/GUI.java
src/nationGen/Settings.java

I got frustrated with constantly having the wrong era selected at startup.  Let's fix that!

Have settings read/written for sacred power/era

---

.classpath
.settings/org.eclipse.jdt.core.prefs

^^ Title
Really.  Java 8 came out in 2014 🗡 
I want to use Set.of ugh

Change java to be current version instead of 4 years old

---

.classpath
.settings/org.eclipse.jdt.core.prefs
src/nationGen/GUI/GUI.java
src/nationGen/restrictions/NationThemeRestriction.java

also known as I'm an idiot and had small yet meaningful mistakes in nationgenassets refactoring, and didn't notice until now.

Java 1.10 Try 2

---

src/nationGen/GUI/GUI.java
src/nationGen/GUI/RestrictionPane.java
src/nationGen/nation/Nation.java
src/nationGen/restrictions/DoubleTextBoxListRestriction.java
src/nationGen/restrictions/MageWithAccessRestriction.java
src/nationGen/restrictions/MagicAccessRestriction.java
src/nationGen/restrictions/MagicDiversityRestriction.java
src/nationGen/restrictions/NationRestriction.java
src/nationGen/restrictions/NationRestrictionFactory.java
src/nationGen/restrictions/NationThemeRestriction.java
src/nationGen/restrictions/NoPrimaryRaceRestriction.java
src/nationGen/restrictions/NoUnitOfRaceRestriction.java
src/nationGen/restrictions/PrimaryRaceRestriction.java
src/nationGen/restrictions/RecAnywhereSacredsRestriction.java
src/nationGen/restrictions/SacredRaceRestriction.java
src/nationGen/restrictions/TextBoxListRestriction.java
src/nationGen/restrictions/TwoListRestriction.java
src/nationGen/restrictions/TwoListRestrictionWithComboBox.java
src/nationGen/restrictions/UnitCommandRestriction.java
src/nationGen/restrictions/UnitFilterRestriction.java
src/nationGen/restrictions/UnitOfRaceRestriction.java

PR to hold restrictions refactoring.  To start, I'm simplifying how the restrictions are checked.  The generate function in Nation.java is much more readable now!
Next step is to remove getinstance of and use a factory instead.
... who knows what I'll do next
this PR depends on new java features (Set.of specifically)

Restrictions Refactoring

---

src/nationGen/nation/Nation.java

This shouldn't got pushed.  Makes an infinite loop.  Not sure how it happened as I don't remember doing this change locally, and I tested before pushing. Must be weird github shenanigans. ah well

Fix stupid mistake from last PR

---

data/filters/default_nationwidefilters.txt
data/filters/default_sacredfilters.txt
data/items/serpentmen/serpentmenbases.txt
data/themes/serpentmen_themes.txt
src/nationGen/magic/MageGenerator.java
src/nationGen/nation/PDSelector.java
src/nationGen/rostergeneration/CommanderGenerator.java

* Tweaked some filter restrictions to avoid e.g. blind races getting better nightvision
* Tweaked some filters so frosty/fiery/gassy units less likely to kill themselves
* Added support for #almostundead when considering national special leadership requirements

Filter tweaks and #almostundead

---

data/filters/default_magefilters.txt
data/races/merrow.txt
data/spells/custom_spells.txt
data/spells/guaranteed_spells.txt

Various 5.26 filters for specialized mage summons bonuses

Foolord mage filters

---

data/themes/default_nationthemes.txt
src/nationGen/naming/Summary.java

Was pointed out this bug in a new game that's started-- morrosnationgen-- on the main dom discord.

Dom4->Dom5.  zombiereanim became priestreanim

---

data/filters/default_specialcommanderfilters.txt

Made dowsing commanders capable of dowsing

---

src/nationGen/NationGen.java

Added support for some newer shapechanges

---

data/names/nations/nordic/longsyllables.txt
data/names/nations/nordic/shortsyllables.txt
data/names/nations/nordic/suffixes.txt

Reverts elmokki/nationgen#1110

Revert "Removing diacritics in Nordic nation names"

---

data/races/advancedhumans.txt
data/races/amazon.txt
data/races/borealhumans.txt
data/races/dynastichumans.txt
data/races/enlightened.txt
data/races/humans.txt
data/races/imperialhumans.txt
data/races/machakans.txt
data/races/orientalhuman.txt
data/spells/guaranteed_spells.txt

* Added Nordic spell sets
* Made human nations typically half as likely to also have another type of humans as a secondary race

Nordic spells

---

data/items/crustacean/crabman/bases.txt
data/items/crustacean/crabman/bases_priest.txt
data/spells/custom_spells.txt

* Added missing parens to Supplicant of Earth definition
* Line troop crabs lose AP on their pincers, +5g/+5rp, elites/coms +5g/+10rp

Custom earth communion bugfix, crab balance

---

data/items/customitems.txt
data/items/ogre/bases_ettinling.txt

I think a little bit of whitespace autoformatting snuck in too
Closes https://github.com/elmokki/nationgen/issues/1137

Fix #natt and #ambidexterous typos

---

changelog.txt
data/poses/amazon/amazoncavalry.txt
data/poses/avvim/avvitecavalry.txt
data/poses/dynastichuman/dustwalkerelites.txt
data/poses/dynastichuman/dustwalkersacreds.txt
data/poses/dynastichuman/dustwalkertroops.txt
data/poses/dynastichuman/dynasticslaves.txt
data/poses/dynastichuman/dynastictroops.txt
data/poses/enlightened/nagatroops.txt
data/poses/human/humancavalry.txt
data/poses/lizard/chariot.txt
data/poses/monkey/vanaraelites.txt
data/poses/orientalhuman/cavalry.txt
data/poses/sidhe/troops.txt
data/poses/sobek/sobek.txt

* As per vanilla, no shields (or DW) for charioteers
* Dynastics troops weren't rendering quivers

Chariot shields, dynastic quivers

---

data/items/avvim/mounted/weapon_chariot.txt
data/items/ichtyid/giant/weapon.txt
data/items/sobek/sobek/weapon_chariot.txt
data/poses/monkey/vanaraelites.txt

Various corrections to needs stuff

#needs fixes

---

data/filters/default_magefilters.txt

* Fixes chargedbody filter
* Adds 4 shockres to that filter as well
* Closes #1145

Charge body fix

---

data/templates/slavetemplate.txt
data/themes/van_themes.txt

* Replaced hasprimaryrace check with primaryrace not van

Fix for vanish serf theme

---

data/filters/default_priestfilters.txt
src/nationGen/magic/MageGenerator.java
src/nationGen/rostergeneration/ScoutGenerator.java

-Fixes magepriest generation for extra mages
-Tidies up and tweaks mage MR adjustments
See description of individual commits below for more details

Mage generation fixes & cleanup

---

data/items/enlightened/dantih/bases.txt
data/items/enlightened/dantih/youth/bases.txt
data/items/foulspawn/medium/head.txt
data/items/foulspawn/mounted/head.txt
data/items/foulspawn/small/debility.txt
data/items/foulspawn/small/head.txt
data/items/illithid/slave/thrall_hoburg.txt
data/monsters/default_monsters.txt
data/monsters/hoburg_monsters.txt
data/races/hoburg.txt
data/themes/gigante_themes.txt
data/themes/hoburg_themes.txt

* #supplybonus -1 -> #appetite +1 (mostly for hoburgs)
* +1 reclimit in the not-currently-active hubristic gigante themes

5.47 Changes

---

data/descriptions/USABLE_DESCRIPTION_STRINGS.txt
data/descriptions/filter_descriptions.txt
documentation/description_commands.txt
src/nationGen/naming/NationDescriber.java

* documentation/description_commands.txt describes the commands used to build descriptions. Also added a few more strings to USABLE_DESCRIPTION_STRINGS.txt
* Added a few missing tags in data/descriptions/filter_descriptions.txt
* Reworded the description for mechanical man transform to play nice with hero descriptions
* Added a few more comments in NationDescriber.java to clarify a few obtuse statements

Added documentation for new description system, fixed a few filters

---

data/descriptions/commander_descriptions.txt
data/descriptions/descriptions.txt
data/descriptions/filter_descriptions.txt
data/descriptions/scout_descriptions.txt
data/filters/default_specialcommanderfilters.txt
data/filters/specialcommanderfilters_extended.txt
data/filters/specialcommanderfilters_hoburg.txt
src/nationGen/naming/NationDescriber.java
src/nationGen/rostergeneration/ScoutGenerator.java

NationDescriber.describeCommanders() now includes scouts and special commanders, with relevant filter descriptions including a very minimal description for scouts based on tier.

Rudimentary descriptions for scouts/special commanders

---

data/items/machakans/colossi/offhand.txt
data/items/machakans/colossi/weapon.txt
data/items/machakans/colossi/weapon_2h.txt
data/poses/machakan/colossi_elites.txt
data/poses/poses.txt
data/themes/austral_themes.txt

Finishing up Colossi to a "playable" state and also making a revamped theme system for australs. Will require new poses and stuff for Machakans and a further pygmy rework thingy

Austral Rework 3

---

data/races/hoburg.txt

Buffs hoburgs a bit having human level defence on 6 hp race is too bad,

vanilla hoburgs are small have +3 def
