- src/nationGen/GUI/GUI.java
- src/nationGen/NationGen.java
- src/nationGen/Settings.java
- src/nationGen/rostergeneration/SacredGenerator.java
- Added an experimental sacred power slider
- Divided settings to settings and advanced settings. Advanced settings
are settings that break seeds if changed.
- Added a numeric code that can be used to quickly load certain
settings. Settings need to be boolean. Default settings are generated
with code 0. This code is written to .dm instead of the old setting
list.
> Options update

- data/races/avvim-slaver.txt
- data/races/avvim.txt
They were using human names. Also, I think regular human names might be
better off made germanicish (but distinct from norse and hoburg names)
rather than random gibberish.
> Avvite name  fix

- data/items/highmen/cavemen/armor_allied.txt
- data/items/highmen/cavemen/offhand_allied.txt
- data/items/highmen/cavemen/shield_allied.txt
- data/items/highmen/cavemen/weapon_allied.txt
- data/items/hoburg/crossbow/weapon.txt
- data/poses/highmen/cavemanallies.txt
- data/poses/poses.txt
- data/poses/sobek/sobekmage.txt
- data/themes/hoburg_themes.txt
- src/nationGen/nation/Nation.java
-Themes used weren't printing out in the .dm because it was trying to
print race(X).themes instead of race(X).themefilters
- Added caveman_allies social theme for hoburgs to give them
better-equipped caveman allies w/in the primary race and a preference
for cavemen mounts
- Tweaks to lower-tech hoburg stats (+1 def / -1 mor)
> Theme doc printout fix

- data/poses/highmen/cavemanallies.txt
- Cavemen allies (as provided by the caveman_allies theme, not secondary races) were not having stats assigned since that's normally handled in their race file
> Caveman allies fix

- src/nationGen/magic/MageGenerator.java
1/2 of max-tier T1 priests are #okleader for +10g
1/8 of other T1s are #okleader for +10g
~1/10 of non-max-tier T1s are #noleader for -5g
1/8 of T1-3 #poorleader priests are #command 30 for +5g
> More diverse bad leaders in the clergy

- src/nationGen/rostergeneration/TroopGenerator.java
#dw_maxlength sets the maximum length of weapon to be eligible for an
offhand weapon. Default is 2.
> #dw_maxlength and debug message removal

- data/misc/gods-austral.txt
- data/misc/gods-occidental.txt
- data/misc/gods-oriental.txt
- data/misc/miscdef.txt
- data/races/agarthans.txt
- data/races/atlantian.txt
- data/races/caelians.txt
- data/races/cavemen.txt
- data/races/fomorians.txt
- data/races/ichtyid.txt
- data/races/machakans.txt
- data/races/muuch.txt
- data/races/orientalhuman.txt
- data/races/sidhe.txt
- data/races/tengu.txt
- data/races/vanir.txt
- data/races/zotz.txt
- data/templates/sloth_magetemplate.txt
- data/templates/templates.txt
- data/themes/hoburg_themes.txt
- src/nationGen/naming/Summary.java
- Defined "western", "eastern", and "southern" homerealm preferences,
and added them to a couple of races and hoburg regional themes
- Added a few more chanceincs based on primaryrace for secondary races
and hoburg regional themes
- Added "#nationcommand '#uwbuild 1'" to the four amphibious races
- Added relatively low-probability hoburg social themes for 5%/10% golem
cults; added handling to output a line describing nations with #golemhp
in Summary.java
> Gods, ally preferences, hoburg golem cults

- data/templates/default_trooptemplates.txt
- malformed argument in patroller 1 template was causing index
out-of-bounds errors
> default_trooptemplates fix

- data/poses/gaian/minotaurmages.txt
- data/poses/gaian/minotaurtroops.txt
Gave all minotaur poses a subrace tag; right now it would be easier to
just get rid of the #visiblename, but aesthetically I'd rather have them
as a subrace of the collective glob of pan-Gaian races regardless of
whether saytrs and centaurs end up being added as demographic themes for
a single overarching Gaian race alongside minotaurs, or as separate
races that tend to ally with each other
>  	Minotaurs labeled as a subrace

- src/nationGen/units/ShapeChangeUnit.java
- src/nationGen/units/Unit.java
- Shape commands were handled twice. This caused issues with repeatable
commands like #weapon
- Racial stats overrode #copystats
> Two shapechange bugfixes

- src/nationGen/units/Unit.java
Also, a sanity check was added so #adjustmentcommand will simply add any
commands that are not already defined
Incidentally, this should run a tiny bit faster than the old way as commands are only checked for adjustment commands if some adjustment commands exist
> adjustmentcommand and basevalue tags were not being processed

- data/filters/default_nationfilters.txt
- data/items/abysian/humanbred/humanmounts.txt
- data/items/amazon/mounted/amazonmounts.txt
- data/items/amazon/mounted/amazonmounts_low.txt
- data/items/human/human_mounted/humanmounts.txt
- data/items/human/human_mounted/humanmounts_low.txt
- data/names/magenames/names.txt
- data/names/magenames/tieredpriestnames.txt
- data/names/sacredbasenames.txt
- data/names/troopnaming/troopmiscitemnames.txt
- data/poses/gaian/minotaurmages.txt
- data/poses/gaian/minotaurtroops.txt
- data/races/advancedhumans.txt
- data/races/amazon.txt
- data/races/lizards.txt
- data/races/machakans.txt
- data/themes/hoburg_themes.txt
- data/themes/van_themes.txt
- documentation/special_commands.txt
- graphics/monsters/supermonsters.txt
Human -> [no change]
Oriental human -> [model; no change]
Human (black) -> Austral human
Human (advanced) -> Advanced human
Human (Amazon) -> Amazon human
This is a cosmetic change mostly made to make the names that just
started being displayed in Adv. Desc. files look a bit more homogenous
and less clunky than the e.g. "(Human (Amazon))" or "(Human (black) -
colossi)" that the current names result in. Also, eliminated Minotaur as
an internal subrace to expunge "(Minotaur - minotaur)" labels; depending
on how the rest of the "Gaian" races are implemented (demographic themes
vs. distinct allied races), it may come back later or stay gone.
> Internal name format consistency for human subraces

- data/items/atlantian/shamblerbases.txt
- data/items/muuch/shamblerbases.txt
In keeping with 4.20, shambler base cost has been reduced to 20g - from
the 30g (!) it currently is, which seems to be based on war shambler
prices even though they have normal shambler stats.
> Shambler cost adjustment

- armor.csv
Not sure how this happened (DB conversion stuff doesn't point to an
immediately obvious explanation, either), but "armorname" had been
renamed "name" in armor.csv, so Advanced Description files, etc. were
all screwed up.
> armor.csv field name error

- data/poses/caelian/troops.txt
Nation seed 145208006 will cause the error.
For 3+ nations, mod seed  -878385423 will result in two good nations
with the race tags "all_troops_sacred" and "all_troops_elite" present,
and the third (145208006) will have neither tag in the race's tag list.
> Example for debugging the elites issue

- src/nationGen/magic/MageGenerator.java
- src/nationGen/units/Unit.java
* magic/demon/undead units who were e.g. getting their status from an item (like basesprite) were not being properly processed because commands[] hadn't had the command added at the point where dSL() was invoked. A call to dSL() was added for all casters at the end of polish(), although that may well not be a good place to add it - also, it looks like non-caster heroes aren't getting special leadership added, so it might be better if this was done for all non-scout leaders instead of just casters.
> determineSpecialLeadership wasn't catching all special types

- src/nationGen/nation/PDSelector.java
PD commander selection was just pulling the first commander off its list every time instead of using the list of valid commanders it generated.
Priest selection was concurrently adjusted because otherwise fixing this meant double PD commanders would result any time a priest was placed at the start of the commander list.
Closes #359
> PD commander fix

- src/nationGen/magic/MageGenerator.java
- src/nationGen/units/Unit.java
I reviewed undead priests and found that of the 32 in vanilla, all but 4 have 80+ undead leadership - there's one with none, and three with 40. Typically, even if they're getting to 80+ partially from having
Death/Blood paths, more than +40 of that is from non-path bonuses.  I added a check in determineSpecialLeadership which will effectively upgrade undead priests' leadership by one level if they have any (so basically +0/+30/+40/+40/+40). This won't give any of the absurd levels some vanilla nations' undead priests enjoy, but it should make lowly undead priests a bit more usable if a nation has multiple tiers.
Demonic priests are much more likely to just be "10 + D/B path bonuses" so I left them as-is.
> Undead priest undead leadership boost

- data/filters/default_priestfilters.txt
The priest healer filters, for no reason I can discern, no longer works
in accordance with the manual - it's currently giving recuperation
instead of healing - and if it did, it would be obscenely strong in
Dom4. I changed healer 10/25/50 to autohealer 1/2/3.
> Priest healer filters not working/really strong

- documentation/special_commands.txt
* In preparing for a hashed-seed hoburg-only MP NG game, found some of
the documentation re: primary/secondary amounts in roster/mage gen to be
opaque or missing. Added documentation for a few unlisted commands and
clarified default values for a few others
> Doc clarifications and additions in re: primary/secondary troops/mages

- data/items/customitems.txt
#singleuse does not work. Added #ammo 1 which should work, but I did not bother testing.
> Bronze lance fix

- src/nationGen/diagnostics/Spritechecker.java
It just tries to read every single sprite and mask defined for an item
and tells if it fails.
Turns out there is a pile of errors, though they just repeat a couple of
file definitions so it'll be easy to fix.
> Diagnostics: Sprite definition validity checker

- data/filters/specialcommanderfilters_extended.txt
* In keeping with longstanding NationGen development priorities, this crucial update adds the most critical new feature from 4.25 to NationGen, namely a filter to allow for commanders who summon swans
* The almost-but-not-quite-as-important features of war swan mounts for pygmies and/or hoburgs will have to wait until I get my grubby little mitts on a 4.25 spritedump
> Swanherds as special commanders

- data/races/agarthans.txt
* 10g -> 9g; this feels entirely reasonable given how awkward these
lumpy sacks of HP tend to be both in vanilla and NG
> 4.25 Pale One price reduction

- data/items/agarthan/generic_big/bases.txt
- data/items/agarthan/generic_big/rangedbases.txt
- data/items/monkey/vanara/caster/magebases.txt
- data/items/monkey/vanara/caster/magebases_float.txt
- data/items/monkey/vanara/caster/magebases_sit.txt
- data/items/monkey/vanara/mounted/bases.txt
- data/items/monkey/vanara/mounted/sacredbases.txt
- data/items/monkey/vanara/normal/bases.txt
- data/items/monkey/vanara/normal/sacredbases.txt
- data/poses/agarthan/agarthanmages.txt
- data/poses/agarthan/agarthantroops.txt
* Reduced all vanara basecosts by 1g (10/15/12/11g->9/14/11/10g for lowland/winged/vanarabred/alpine)
* Reduced olmspawn basecosts from 30g->25g (in-game sacred unit is 45g->35g)
* Reduced ancient pale one basecosts from 35g->30g (in-game sacred units are 50g->40g)
> More 4.25 pricing updates

- src/nationGen/rostergeneration/SacredGenerator.java
I'm fairly certain this was a bug and not a data error, anyway: #caponlychance is currently used in the data files as a double from 0 - 1, and SacredGenerator was trying to read the arguments to #caponlychance by doing a cdr of the argument, so if the caponlychance was 1 (or 0) it would have an array index out of bounds exception.
> Fixed bug with highestcaponlychance

- src/nationGen/rostergeneration/ScoutGenerator.java
* Ugly implementation of scout survivals in scoutgenerator; scouts (and only scouts) who do not have flying, mounted, amphibian, aquatic, or 3+ survivals from their race/pose/items/etc. will have enough survivals added to give them at least 2 and a 25% chance of 3, with priority given in order of mountain (because this increases mobility)>forest>waste (because mountain/forest/swamp is the most common trio)>swamp, with the exception that scouts with native swamp survival (and no other survival) will favor forest first and mountain second.
* Closes #513
> Survivals for scouts

- data/items/agarthan/generic_big/bases.txt
- data/items/agarthan/generic_big/rangedbases.txt
- data/poses/agarthan/agarthanmages.txt
- data/poses/agarthan/agarthantroops.txt
* Per KO, their price reduction was inadvertant, so now they cost the same amount as Ancient Ones. The basecost in-game for those is 33g, so I bumped their prices up from 30g to 33g as well
> Revert Olmspawn changes, tweak Ancient costs

- src/nationGen/magic/MageGenerator.java
* Misplaced paren turned int addition into string concatenation, with the end result of making priests get e.g. #gcost +200 rather than #gcost +20 ("#gcost +" + (int)(20) + (int)(0) rather than "#gcost +" + (int)(20 + 0)...)
> Priest cost bug

- data/items/human/scout/bonusranged_scout.txt
- data/items/illithid/hybrid/armor.txt
- data/poses/amazon/amazoninfantry.txt
- data/poses/human/humaninfantry.txt
* These are all themed by region, so I probably should make distinct scout poses for regional humans who don't have them so they can use these. Plus, obviously, add a bit more weight to the regional themes so e.g. oriental humans are more likely to have shuriken and less likely to have throwing axes.
* Random fix for a illi hybrid armor id error
> More missiles for generic-human-set scout bonus weapons

- data/themes/default_nationthemes.txt
- src/nationGen/magic/MageGenerator.java
Old system was very biased towards H1. Now it's biased more towards H2.
Also a slight increase in amount of stand alone H2 priests even if you
have priest-mages.
> Priest level distribution tweaks

- src/nationGen/naming/NationAdvancedSummarizer.java
* Changed montag unit list label from "Sacreds" to "Sacreds and Elites" (I know there's enough info already there that this wasn't quite ambiguous, but it still managed to confuse some people)
> Clarification of montag adv. descs

- data/names/nations/nordic/longsyllables.txt
- data/names/nations/nordic/shortsyllables.txt
These ones are a bit better than previous ones:
Hedersand (= Honorsand) Bomarrus Lusand Kirkmarsand Falkenberg (= Falconmountain) Arnorus Saltgar Lilleberg (= Smallmountain) Enholm Thorssund (= Thor's sound) Saltborg (= Salt fortress) Margard Lekholm (Playisland (archaic form of island)) Falkenheim (Falconland) Nyarp Korsengard (Cross or dagger courtyard) Åleholm (Ale island) Kramvik (Embrace bay) Farsund (Father sound) Vanmunstad (Van mouth city) Vaxgard (Wax courtyard) Dranosund (Drain-o-sound) Narheim (Whenland) Odinsmunsand (Odin's mouth's sand) Draholm (Drain island) Ögard (Island courtyard) Kramhamn (Embrace harbour) Bollrus (Ballrus) Falkenping Kramheim (Embrace land) Luland Enerrus (Thousands rus) Luheim Korskulborg (Dagger fun fortress) Bosjo (Estate/Nest/To house/To live island) …
> Should've tested names more

- data/names/troopnaming/troopmiscguaranteedparts.txt
- data/names/troopnaming/troopspecialprefixes.txt
- documentation/special_commands.txt
- src/nationGen/magic/MageGenerator.java
- src/nationGen/misc/ChanceIncHandler.java
- src/nationGen/naming/Name.java
- src/nationGen/naming/NamePart.java
- src/nationGen/naming/TroopNamer.java
- src/nationGen/units/Unit.java
Troop naming now:
- Adds nationality prefix ("Ulmish") since units tend to have identical names across nations so often.
- Tries to shorten names when there's redundancy in item based names
Example of the second: You have three "Spear Warrior" named units after first weapon set. The program differentiates them to "Spear Javelineer", "Spear Warrior" and "Spear Axe Thrower". This look stupid. Now the program will check whether removing prefix (or prefixprefix) on any pair results in duplicates. Since Warrior != Axe Thrower != Javelineer, the program removes all prefixes. 
However, if the nation also had an "Axe Warrior", the "Spear Warrior" would keep the name since Warrior = Warrior.
I changed the order of resolving things somewhat too.
> Troop naming update and misc changes and bugfixes

- data/names/troopnaming/troopmiscguaranteedparts.txt
* This should hopefully be more correct in doing what is intended with faux-chariot mounted units; I presume that this is where the "pale one chariot" came from, even though I couldn't duplicate the bug
* I probably should just give in and make these into proper chariot poses instead of cutting corners since it's now swan AND rat chariots (and could easily be expanded to goat and pig "small chariots", too), but for now I'll leave it in its kludged form
> Tweaking fake chariot names

- data/items/foulspawn/mounted/legs.txt
- data/poses/poses.txt
- data/races/illithid.txt
* Turned on the illi thralls that have been added. They're there, so there's no reason not to add them even if it means that some secondary races are better than others for the starkids
* Added winged olm-centeroid FS: because why not?
* Fixed a few instances of #amphibious -> #amphibian, because if I didn't periodically but consistently make these sorts of typos it just wouldn't be the same
> Illi thralls turned on, winged olm FS

- src/nationGen/rostergeneration/CommanderGenerator.java
* If a nation has animal troops, it is possible that their commanders will get beastmaster 1-2
* Taskmaster and beastmaster now cost bonus*5g
* #slave commanders always get taskmaster 0-2 (50% chance of 0); if taskmaster > 0, they will also get an inspiration penalty of 0-taskmaster (and get a corresponding gcost reduction of penalty*10g); their overall cost will therefore be modified by -10g (tm +2/ins -2) to +10g (tm +2/ins +0)
* #animal commanders always get beastmaster 0-3 (50% chance of 0); if beastmaster > 0, they will also get an inspiration penalty of 0-beastmaster (and get a corresponding gcost reduction of penalty*10g); their overall cost will therefore be modified by -15g (bm +3/ins -3) to +15g (bm +3/ins +0)
* Essentially, the above allows for non-standard troops to have …
> Specialized national commanders (slave/animal)

- data/poses/agarthan/agarthanmages.txt
- data/poses/amazon/amazonmage.txt
- data/poses/atlantian/mages.txt
- data/poses/fomorian/giants.txt
- data/poses/halfmen/minotaurmages.txt
- data/poses/monkey/vanaraelders.txt
- data/poses/muuch/mages.txt
- data/poses/sidhe/mages.txt
- data/poses/vanir/mages.txt
- src/nationGen/magic/MageGenerator.java
* Casters with the "warriormage" tag will get leadership ranging from 10 to 120, with (slightly discounted) gcost bumps according to the standard scale of costs; about 3/4s of them will have leadership falling between 10+30 and 40+20
* Currently warrior-mages include some  (or in a few cases, all) varieties of: pale ones, amazons, Atlantians, muuch. Fomorian giants, minotaurs. vanara, vanir, and sidhe
> Better leadership for warrior-mages/priests

- data/items/foulspawn/medium/lleg.txt
- data/items/foulspawn/medium/rleg.txt
- data/items/foulspawn/small/caster/lleg.txt
- data/items/foulspawn/small/caster/rleg.txt
- data/items/foulspawn/small/lleg.txt
- data/items/foulspawn/small/lleg_scout.txt
- data/items/foulspawn/small/rleg.txt
- data/items/foulspawn/small/rleg_scout.txt
- data/poses/agarthan/agarthanmages.txt
- data/poses/agarthan/agarthantroops.txt
- data/poses/foulspawn/small/cavalry.txt
- data/poses/foulspawn/small/infantry.txt
- data/poses/foulspawn/small/mages.txt
- data/poses/foulspawn/small/ranged.txt
- data/poses/illithid/hybrid_cavalry.txt
- data/poses/illithid/hybrid_infantry.txt
- src/nationGen/units/Unit.java
Let me preface this by admitting that my changes probably make this more involved and less intuitive than how it was before.
This is a messy fix which works for how the files are written but may not work with how they were supposed to be written. However, as I couldn't see how to make them work with what had been in place, I went ahead and "fixed" things. It also seemed like it had some redundancy in it to start with, which made me kinda leery when changing things. The code feels sloppy (yes, I know, I always say this), but it appears to work fine in testing.
Basically, FS were getting *a lot* of hands and/or misc slots. Oh, and not enough heads if they had two heads, IIRC. The old way did not allow for poses, etc. to set a base number of slots. I think. Maybe. Some units looked …
> Foulspawn slot weirdness

- data/spells/custom_spells.txt
- data/spells/random_spells.txt
* Added custom enchantment-based nature-only crossbreeding spells possible only for FS nations.  Nature must be the highest path, and having blood significantly reduces the chance of it being present, as does high diversity. Costs the same amount of gems as the original costs slaves, but an extra 5/10 FS (and +2/+4 per level) are produced.
* Earth communion spells fixed as they had not actually required earth instead of astral.
> Non-blood crossbreeding as a possible FS custom spell

- src/nationGen/NationGen.java
- src/nationGen/nation/Nation.java
- src/nationGen/rostergeneration/UnitGen.java
- src/nationGen/units/Unit.java
Ids were being handled during generation, resulting in theoretical
ability to run out of ids if a very large amount of montag units were
generated in discarded nations.
Now there's a mock id of type "nationX_-Y" being handed and actual
montag ids being given when shapeshift ids are being given.
> Montag id handling fix

- data/items/avvim/nephilim/bases.txt
- data/poses/illithid/illithid_mages.txt
- data/poses/illithid/illithid_troops.txt
- data/poses/illithid/slaves.txt
* Illithid have no subrace now (they're illithid, after all), but assorted lobo guards have assorted subraces
* Nephilim forced to subsist on a meager 120 people per month instead of their more-palatable serving size of 1200 in the current data
> Illithid subrace improvements, nephilm go on a diet

- data/spells/random_spells.txt
* Previously the lower-numbered unresearchable no-cost/no-fatigue/non-sacred-boars version of the spell (96) is selected instead of the Marverni sacred-boar ritual summon (172). Changing it to 172 makes random boreal/nature nations revere boars as sacred as a side effect, but it should solve the more pressing problem.
* Closes #830
> Sounder of Boars fix

- data/filters/default_magefilters.txt
* T1/T2/T3 get +/- 20/40/60gcost worth of upkeep (so +/-16/32/48g per year, or half that if sacred)
* As suggested in #839
> Scaling mage upkeep filter

- data/filters/filters.txt
- data/filters/specialcommanderfilters_extended.txt
- data/filters/specialcommanderfilters_hoburg.txt
- data/items/hoburg/crossbow/armor.txt
- data/items/hoburg/crossbow/armor_oriental.txt
- data/items/hoburg/crossbow/armor_oriental_light.txt
- data/items/hoburg/crossbow/bows.txt
- data/items/hoburg/crossbow/weapon.txt
- data/items/hoburg/mounted/armor.txt
- data/items/hoburg/mounted/armor_light.txt
- data/items/hoburg/mounted/cavalryweapons.txt
- data/items/hoburg/mounted/cavalryweapons_oriental.txt
- data/items/hoburg/mounted/mounts.txt
- data/items/hoburg/mounted/shields.txt
- data/items/hoburg/mounted/stealthymounts.txt
- data/items/hoburg/normal/helmet.txt
- data/items/hoburg/normal/helmet_oriental.txt
- data/themes/hoburg_themes.txt
* Feral/agrarian hoburgs are slightly/much-more-likely to have special commanders; these will be either various chaff-summoners (a modified version of the extended filterset) or light-troops-as-special-commanders "forager/raiders"; in either case, these will grant supply bonuses (whether the summoner produces dogs, scorpions, or markatas; it's all meat...)
* Gave all special commanders with magicbeing or imp summoning a small amount of the associated command, even if right now it doesn't appear that specialcommanderfilters_extended is actually in use
> Hoburg special commander filters

- src/nationGen/misc/PreviewGenerator.java
Previously, like ages ago, flags were generated when writing the mod and thus there was separate flag generation using the same seed in preview and mod writing step. At some point flag generation was made sensible and flags were drawn during generation and stored, but previews were not changed. I'm not exactly sure what caused the bug, but it's probably relatively simple and fixing it by actually using the nation flag from the nation saves computing power so why not.
Closes #885
> Preview flag fix

- data/items/abysian/humanbred/mounts.txt
- data/monsters/hoburg_monsters.txt
* Humanbred scorpion riders were using the old sprite size's offsets
* Boreal giant hoburgs had an errant copystats from war elephants in
their definition; the only thing it did was make them count as animals,
which was funny, but not intended
> Small fixes

- src/nationGen/magic/MageGenerator.java
* Simple recruitment point implementation for mages: if they previously got #slowrec, they now get #rpcost 4; o/w they get #rpcost 2
* Mostly-simple recruitment point implementation for priests: H3 is either RP4 if they were previously slowrec, and RP2 o/w; H2 is RP2; H1 is RP1 unless they have #goodleader or better, in which case they are RP2
* Added a few more higher-than-average leadership options for warriormage priests and H3/H2 priests
* Fixed a weird error that was preventing any H3s from being slowrec or cap-only, or any priests from getting non-standard leadership values
> Recruitment points for mages and priests

- src/nationGen/misc/ChanceIncHandler.java
Now pretty much everything should accept both:
not <chanceinc> <args> value
and
<chanceinc> not <args> value
For some chanceincs there is a difference. These are generally multi-argument chanceincs. For example, all the "slot has tag" ones tend to work better with the latter example, since then it is true if slot x contains said theme and false otherwise. Former example would instead be true as long as slot x did not contain the tag, which is kind of disastrous for stuff like "this unit should not get any chest armor which isn't for armored units" since it turns it to pretty much the opposite. This was the issue before with the particular foul spawn, but it was fixed separately.
This should close #939
> Even more ChanceIncHandler rewriting!

- settings.txt
- src/nationGen/nation/PDSelector.java
NationGen had been doing a reasonable job of getting PD numbers so long as the troops had fairly close to average res/gold, but they were ending up with some fairly outrageous outliers (e.g., nations with slaves who were ending up with close to 30 per 10). Vanilla is pretty dull on this count, and has nations showing up with 10 troops per type across a whole range of res costs, but rarely gets above 15 per and never above 20 per.
I fixed the code so it was actually doing what it claimed in re: the resMultiT[h]reshold. I also added checks so upper threshold modifiers couldn't reduce res/gold below the threshold, nor lower ones above the threshold. This eliminated some weird things like "13 & 15 are worth 13 res points but 14 is worth 12"; in this case (14/-2) it's now 13->13, 14->14, …
> PD number changes

- data/filters/default_specialcommanderfilters.txt
* Added a bunch of alternate titles for generic special commanders
* Added #mason special commanders (it might not be a bad idea to add a specific mention in national descriptions when these show up, but I'm not too worried about it; the special commanders should show up in those, and Dominions automatically mentions if a nation has masons when displaying its description in-game)
> Special commander titles, #masons

- src/nationGen/nation/Nation.java
* As 5.23 fixed the bug with 3-4 ranks of PD, the feature to occassionally use those is re-implemented.
* Closes #961
> Re-implement variable PD ranks

- src/nationGen/GUI/RestrictionPane.java
- src/nationGen/nation/Nation.java
- src/nationGen/restrictions/RecAnywhereSacredsRestriction.java
This will allow people to filter out sacreds such that only recruit anywhere sacreds appear.  Seems like a good feature to have!
I also cleaned up the includes a bit in RestrictionPane.java since if you're including all the restrictions may as well just use .* instead.
Let me know if there's anything to be changed for style. Cheers
> Add Restriction Type for Recruit Anywhere Sacreds

- src/nationGen/NationGen.java
For some reason, the append operation of Swing's log frame isn't constant time. This means that with too much text in the log frame, the UI freezes.
So, the fix?
Reduce log spam significantly.
I highly doubt any non-dev cares why a seed fails, especially thousands of them. So, I moved that to debug prints only. Then, I added an occasional print (every 250 gens), so they know that *something* is happening.
Here's what the new output looks like! (pretend the -'s exist, I put them back in after the screenshot)
> Fix UI Sluggishness When Generating Large Nation Amounts

- src/nationGen/GUI/CommandLine.java
- src/nationGen/GUI/ConsoleGUI.java
- src/nationGen/GUI/GUI.java
- src/nationGen/NationGen.java
- src/nationGen/magic/MageGenerator.java
- src/nationGen/nation/Nation.java
With my last change, I noticed a user in discord running nearly a million iterations.  That's 0.02% of the seed space itself. Unacceptable.
Anyways, change the type of the seed from Integer to Long. While, this technically appears to not change the result of a given nation, it will change stuff if you use a fixed seed to generate an assortment of nations.
NOTE: I haven't tested the console. But, I've tested the GUI fairly extensively, IMO.
> Make Seeds 64 Bits

- src/nationGen/NationGen.java
Mods directory doesn't exist by default in the working dir of Eclipse when running this project [the root of the repo].  So, you need to use mkdirs. Then, the mod directory exists. This will fix the failed exports when running in IDEs.
> Fix Natgen Export in IDE

- src/nationGen/GUI/ConsoleGUI.java
- src/nationGen/GUI/GUI.java
- src/nationGen/NationGen.java
- src/nationGen/Settings.java
- src/nationGen/nation/Nation.java
- src/nationGen/nation/PDSelector.java
- src/nationGen/rostergeneration/SacredGenerator.java
Adding enums will make the code easier to use without mistakes. I removed a few export values that weren't referenced anywhere in the codebase.  So, would be useless.  If I made a mistake in removing the exports, that's trivial to reverse so I'm going to just merge.
> Settings improvements: Enums/type Safety

- .classpath
- .settings/org.eclipse.jdt.core.prefs
Reverts elmokki/nationgen#1007
Seems like this won't be as simple as just iterating the version.  The data loading of restrictions seems a bit borked. Going to revert while I investigate what's up.
> Revert "Change java to be current version instead of 4 years old"

- data/spells/custom_spells.txt
* Contact spells to summon living sidhe sorceresses fixed so they no longer summon undead Bean Sidhe regardless of the spell cast.
* Changed Contact Foo Sidhe spell descriptions to make it more clear that these summon mages with upkeep
> Contact Foo Sidhe fixes

- data/items/nordic/generic/beard.txt
- data/items/nordic/generic/beard_elite.txt
* So apparently vanir never had any nametype specified?!? Now males get 115 and females 116
> Vanir get Norse names

- data/names/nations/nordic/longsyllables.txt
- data/names/nations/nordic/shortsyllables.txt
- data/names/nations/nordic/suffixes.txt
* Dominions is Nagot gic fel-ing when Nordic nations have diacritics in their names, so all name parts with letters featuring diacritics have had the letters replaced with uninflected versions of the same letter
> Removing diacritics in Nordic nation names

- data/items/atlantian/standard-s.txt
- data/items/atlantian/standard.txt
- data/poses/atlantian/infantry.txt
- data/poses/highmen/cavemanallies.txt
- data/poses/highmen/cavemanmages.txt
- data/poses/imperial/sacred.txt
- data/poses/merrow/troops.txt
- data/poses/monkey/vanaraelites.txt
* Fixes for the missing slots in renderorder
* This includes the probably-dates-back-to-Dom3 errors with Atlantian lobstermen and  standardbearers, so Atlantians are suddenly going to start producing those in entirely unreasonable quantities, which means I need to finally stop putting off modernizing Atlantian race definitions and adding themes to them
> Missing slot fixes

- src/nationGen/restrictions/UnitCommandRestriction.java
Add a way to filter by recruit type in unit command restriction combobox
> :Cap-only and normal filters in UnitCommandRestriction

- data/poses/hoburg/clockworktroops.txt
- data/poses/hoburg/clockworktroops_bronze.txt
- data/poses/hoburg/clockworktroops_oriental.txt
Turns out some specialslots items have #needs handslots tags, so the lists have to be loaded or otherwise an exception will be thrown when generating the nation.
> Restored previously removed #load handslots commands to clockworks
